### ISSUE TITLE
Buscar local para avaliar

### ISSUE THREAD

**Issue by pedrozan** [aceleradora-TW/nao-me-calo#1]
<b>Como</b> Josefa
<b>Quero</b> buscar um local
<b>Para</b> poder realizar uma avaliação

<b>Critérios de aceitação</b>:
- Ao iniciar preenchimento opções aparecem
- Opções mostram o endereço
- Ao selecionar opção sou direcionado para pagina da avaliação do local

**Tasks**
- Botão e Método de Busca: Botão "Buscar" que ao ser clicado pega o valor do campo e repassa para o método que fará a busca no Google Places e redireciona para a página de avaliação
- Autocomplete: Completar automaticamente o campo de busca com o Google Places, mostrando o endereço

<b>Notas</b>:
- A ideia é usar o Google Places.

**Comment by aolchik** [comment]
Buenas! 
Falamos de não usar uma persona muito específica quando isso não é necessário, por outro lado, usário, é um papel muito genérico. Será que aqui não seria melhor o termo oprimido?

O que significa o features:4?
Abs

**Comment by cschallenberger** [comment]
Usamos o termo 'usuário' porque o site pode/deve ser acessado por qualquer pessoa que presencie alguma situação indesejada com algum oprimido, então achamos melhor usar usuário, que abrange qualquer pessoa que deseje relatar algo. Mas amanhã falo com o pessoal para rever isso...
Features:4 é o número da feature em que a história foi baseada.

Abraços

**Comment by aolchik** [comment]
Ok. Pensem o seguinte, além dos oprimidos teremos os administradores do website e, eventualmente, os próprios estabelecimentos. Usuário significa todos eles.
No caso das histórias de usuário é interessante utilizar um papel que seja o principal relacionado a história, mas não precisa necessáriamente englobar todos eles.

**Comment by othman853** [comment]
### Code Review 

_Observação: Este mesmo review foi feito para a estória 1. Favor considerar estes mesmo critérios para ambas estórias (quando estes forem relevantes)._

**Estória #4 Buscar Local para visualizar. Aprovada**.

**Estória #1  Buscar Local para avaliar. Não aprovada:** 

     Adicionar testes unitários para a rota `app/controllers/ratings_controller.rb`

##### Mesmo com a estória 4 aprovada, eu ainda recomendaria pelo menos a correção dos os itens abaixo: 

- 0
- 1 
- 2.1
- 5.1
- 5.3
- 5.5
- 5.7
- 6.1
- 6.4


**0.** Quando possível, descrever melhor como utilizar o projeto usando o README (é uma prática indispensável para projetos open source como o de vocês :p)
**1.** Evitar misturar nomenclaturas em inglês e português.**

Exemplo em `app/views/welcome/index.html.erb`

`#formAvaliar`

`#formSearch`

É mais intuitivo adotar uma única língua nas nomenclaturas, por exemplo:

`#formAvaliar`

`#formBuscar `

ou

`#rateForm`

`#searchForm`

**2 - app/controllers/ratings_controller:**

**2.1** Não tem testes :(
**2.2** Está com a chave da API da Google Hardcoded (linha 20)
**2.2.1** http://stackoverflow.com/questions/3295889/how-do-i-store-keys-for-apis-in-rails
**2.2.2** Juntamente ao recomendado no link acima, acredito eu que para ambientes de produção seja interessante manter estas chaves em variáveis de ambiente (conforme nossa sessão de Shell hehe :p) 


**3 - app/controllers/welcome_controller:**
**3.1** Tem testes relevantes para a estória 1 :)
**3.2** Não tem nada a ver com as estórias, mas tem um caso de teste comentado :p


**4 - Arquivo vazio:**
`app/views/welcome/search.html.erb`

**5 - app/assets/javascripts/welcome.js:**
**5.1** Indentação do código está com espaços à mais
**5.2** Muitos comentários da documentação do google places
**5.3** Variável placeSearch não utilizada
**5.4** Binding redundante de eventos que executam um mesmo comportamento (utilizar o recurso de first class citizens das functions de javascript para corrigir isso):
Ver refactoring (**item 7**)
**5.5** document.getElementById ao invés de seleção jQuery
**5.6** searchBox foi definida sem var. Talvez tenha havido uma confusão entre placeSearch em desuso e searchBox como variável global?
**5.7** variável input nao utilizada em initAutoComplete

**6 - app/views/welcome/index.html.erb:**
**6.1** Binding de evento (onfocus) no HTML. Fazer binding no jQuery
**6.2** Alternativamente, fazer binding no loading do documento, assim, o site pede para ativar localização assim que o usuário entrar na página, ao invés pedir somente quando clicar no campo (muitos sites (o próprio google, por exemplo) usam a primeira opção)
**6.3** Binding onSubmit de ambos forms search e avaliar estão utilizando a mesma função de preenchimento dos campos
**6.4** Nomes confusos nos campos de autocomplete :
Campo avaliar se chama campoBusca
Campo buscar se chama buscarLocal

### 7 - Refactoring sugerido
Talvez o @thiagoxvo  possa dar mais dicas em relação ao refactoring de Javascript isso, mas aqui vão umas sugestões que pensei:

Ao inicializar o documento:

    $(document).ready( function() {

        geolocate();

        $('#rate-form').on('submit', onSubmitSearchBoxForm);

        $('#search-form').on('submit', onSubmitSearchBoxForm);

    });


A função de **geolocate()** é chamada no **onLoad (ready)** do document. Desta forma, a localização é requisitada ao usuário quando ele/a entra na página, ao invés de ser pedida no momento em que ele/a foca no campo de busca/avaliação.

Notem também que os bindings de evento ‘submit’ de ambos os forms são feitos através da função **on** do jQuery. 

_Além disso, a mesma função é usada para ambos os forms, já que antes existiam duas funções para executar o mesmo comportamento._ 



    var initAutocomplete = function initAutocomplete() {

        searchAutoComplete = new google.maps.places.Autocomplete(
          ($('#search-autocomplete')[0]),
          {types: ['establishment']});


        rateAutoComplete = new google.maps.places.Autocomplete(
          ($('#rate-autocomplete')[0]),
          {types: ['establishment']});

        searchAutoComplete.addListener('place_changed', updatePlaceIdPlaceholder.bind({     googleAutocomplete: searchAutoComplete, form:'#search-form'}));
        rateAutoComplete.addListener('place_changed',updatePlaceIdPlaceholder.bind({ googleAutocomplete: rateAutoComplete, form:'#rate-form' }));
    }

Adotar JQuery para buscar os campos de busca e avaliação ao invés de document.getElementById. Renomear tanto as variáveis quanto os ids e classes no HTML, para ficar mais fácil de se achar. Notem que a mesma função *(updatePlaceIdPlaceholder)* escuta os eventos de place changed de ambos os campos. 

    function updatePlaceIdPlaceholder() {

        var place = this.googleAutocomplete.getPlace();

        $(this.form)
            .find('.place-id-placeholder')
            .val(place.place_id);
    }

Esta função por sua vez, tem sua referência this sobrescrita pelo *bind() chamado no addListener*. Sobrescritemos this por um objeto com os atributos googleAutoComplete e form para facilitar a vida. Notem também que os campos place_id e place_id_2 lá do html receberam uma classe em comum (place-id-placeholder) para que esta função funcione com ambos.
