### ISSUE TITLE
Navegar mapa

### ISSUE THREAD

**Issue by WilliamCSA04** [aceleradora-TW/nao-me-calo#10]
**Como** Josefa
**Quero** visualizar locais no mapa
**Para** localizar facilmente um local

**Critérios de aceitação:**

- Iniciar mapa na posição atual do usuario.

**Task:**

- Inserir mapa: Colocar o mapa na home page iniciando na localização atual do usuário.

**Notas:**

- Verificar qual API do google será usada
- Verificar acessiblidade do google maps
- Mostrar o mapa no perfil do local

**Comment by inajaraleppa** [comment]
1. Não será necessário mostrar o mapa no perfil do local, apenas na home.
2. Esta estória seria apenas para visualizar o mapa, sem possuir nenhuma informação nele, correto?
3. API: https://developers.google.com/maps/ (n sei se essa nota era para nós)
4. Não entendi este critério: **Ter o mapa com locais marcados**

**Comment by pedrozan** [comment]
2. O mapa ainda não irá ter informação alguma alem da localização.
4. Os locais marcados são onde já houveram avaliações.

**Comment by inajaraleppa** [comment]
Oi Pedro, mas a parte de colocar os locais marcados não entra na estória do PIN?

**Comment by pedrozan** [comment]
Tem razão iremos editar a estória
