### ISSUE TITLE
Tags na página de avaliação

### ISSUE THREAD

**Issue by pedrozan** [aceleradora-TW/nao-me-calo#11]
<b>Como</b> Leopoldo
<b>Quero</b> fazer uma avaliação com facilidade
<b>Para</b> classifica-lo conforme minha experiência no ambiente

**Critérios de aceitação:**
- trocar os radio button por tags
- adicionar cores aos tags
- remover "não avaliado"

**Notas:**
- História ficará para MVP2

**Comment by pedrro** [comment]
Estória validada, só tinha css e JS(com abuso de JQuery né?! Vamos tomar cuidado com esse jquery desnecessário).
