### ISSUE TITLE
Selecionar fale conosco

### ISSUE THREAD

**Issue by cschallenberger** [aceleradora-TW/nao-me-calo#13]
<b>Como</b> Josefa
<b>Quero</b> entrar em contato com o responsável do site
<b>Para</b> reportar problemas ou dar sugestões

**Critérios de aceitação:**
- Campo para escrever mensagem (campo obrigatório)
- Campo de nome
- Campo de e-mail (campo obrigatório)
- Campo de assunto 
- Retornar mensagem de sucesso

**Tasks**

- Criar a página: criar a página, com o campo para escrever a mensagem, e **ao enviar, mandar para o e-mail do site e das P.O.s**

**Notas:**
- Enviar o e-mail para as P.O.s

**Comment by pedrro** [comment]
Sua estória foi validada com sucesso!

O código em sí está bom. Tem os testes funcionais e unitários. Tem bastante coisa feita com jQuery que poderiam ser feito rapidamente com JS vanilla.

Leitura recomendada:
http://youmightnotneedjquery.com/
