### ISSUE TITLE
Descrever o relato

### ISSUE THREAD

**Issue by cschallenberger** [aceleradora-TW/nao-me-calo#14]
<b>Como</b> Josefa
<b>Quero</b> descrever um relato
<b>Para</b> divulgar minha experiência no estabelecimento

**Critérios de aceitação:**
- Campo para escrever o relato na página de avaliar o local
- Criar filtros para palavras ofensivas e qualquer palavra que configure crime

**Tasks**

-  Criar campo de texto: criar o campo para o usuário escrever o relato
- Criar os filtros: criar os filtros que selecionarão os relatos que serão publicados

**Notas:**
- 500 caracteres 
- Ver com as P.O.s o que cai no filtro

**Comment by thiagoxvo** [comment]
Fala pessoal, segue minha revisão do código, como estou na onde do JS com vocês, foquei em alguns pontos que podemos melhorar:  

Arquivo **ratings.js**  
```javascript
function hasBadWords(text){
  var count = 0;
  var textLowerCase = text.val().toLowerCase();
  for(var i = 0; i <= badwords.length; i++){
    if(textLowerCase.indexOf(badwords[i]) !== -1 ){
      count++;
    }
  }
  badWordsErrors(count, text);
}
```

Na função acima, precisamos da quantidade de badwords ou quando encontrarmos uma podemos parar de iterar no array?
(Essa eu deixo pra vocês refatorarem e me mostrarem amanhã)

```javascript
function badWordsErrors(count, text) {
  if(count>0){
    errors["description"] = true;
    text.addClass( "errorBorder" );
    $( '#descriptionAlertText' ).removeClass( "hidden" );
    $('#descriptionAlert').addClass("text-field-error");
    showMessage();
  }
  else {
    errors["description"] = false;
    text.removeClass( "errorBorder" );
    $( '#descriptionAlertText' ).addClass( "hidden" );
    $('#descriptionAlert').removeClass("text-field-error");
    showMessage();
  }
}
```
Na função acima:
- Cuidar ao utilizarem " ou ', tentem manter um padrão
- Cuidar ao utilizarem espaços, tentem manter um padrão

Esse código poderia ser refatorado de uma melhor maneira, o que acham?
Sugestão (não rodei aqui pra ver se funciona):

```javascript
function badWordsErrors(count, text) {
  var hasError = (count > 0);
  errors['description'] = hasError; 
  text.toggleClass('errorBorder', hasError); //Deem uma olhada em http://api.jquery.com/toggleclass/
  $('#descriptionAlertText') //Deem uma olhada em http://api.jquery.com/toggle/
    .toggle(hasError)
    .toggleClass('text-field-error', hasError)
  showMessage();
}
```

```javascript
function showMessage(){
  if (!$(".radio-button").is(":checked")){
    $( "#radioButtonId" ).addClass( "errorBorder");
  }else{
    $( "#radioButtonId" ).removeClass( "errorBorder");
  }
  for(var l in errors){
    if(errors[l] === true){
      $('#submitButton').prop("disabled", true);
      return;
    }
  }
  if(enableButtonTerms()){
    $('#submitButton').prop("disabled", false);
  }
}
```

Na função acima existem pequenas melhorias que podem facilitar a leitura do código, como:
- Guardar `!$(".radio-button").is(":checked")` em uma váriavel com um nome significativo. Eu demorei pra ver a negação ali
- Utilizar essa váriavel com o metodo toggleClass do jQuery para evitar o if/else
