### ISSUE TITLE
Compartilhar relato/ranking

### ISSUE THREAD

**Issue by cschallenberger** [aceleradora-TW/nao-me-calo#16]
<b>Como</b> Josefa
<b>Quero</b> compartilhar um relato nas redes sociais
<b>Para</b> divulgar o fato ocorrido no estabelecimento

**Critérios de aceitação:**
- Permitir compartilhamento dos relatos (Facebook, Twitter)
- Permitir compartilhamento do ranking (Facebook, Twitter)

**Tasks**

- Criar botão de compartilhamento: criar o botão que linka o Nao Me Calo com a rede social
- Criar o post: formatar o relato/ranking para ser compartilhado

**Comment by ebragaparah** [comment]
Galera, deixei uns comentários nos commits. Dêem uma olhada. Não acredito que seja um obstáculo para a estória seguir, mas são pontos que podem ser melhorados, olhados de uma outra maneira para ver se faz sentido.
