### ISSUE TITLE
Criar Admin

### ISSUE THREAD

**Issue by silvinho485** [aceleradora-TW/nao-me-calo#17]
#<b>Como</b> admin
<b>Quero</b> tornar outra pessoa admin do site
<b>Para</b> permití-la administrar o site

**Critérios de aceitação:**
- Criar um novo admin

**Tasks**
- Criar admin
- Verificar se admin existe

**Comment by inajaraleppa** [comment]
Oi, 

Vocês não acham melhor ter uma estória só para o Admin e outra para o visualizar e deletar relatos?

**Comment by WilliamCSA04** [comment]
Boa tarde, nós estamos na dúvida do que iria na estória do Admin, teria mais alguma coisa que o admin iria fazer além de aprovar e remover os relatos?

**Comment by inajaraleppa** [comment]
@WilliamCSA04 Oi,

Poderíamos cadastrar novos admins, editar admins, excluir admins. 
No cadastro do admin teria um login/email e senha e essas informações poderiam ser alteradas em algum momento.

Acho que seria isso, faz sentido?

**Comment by WilliamCSA04** [comment]
Boa tarde, isso que tu falou faz sentido, porém vamos avaliar um melhor forma de quebra estas estórias.

**Comment by maedabr** [comment]
## Code Review

Os comentários que escrevi aqui em baixo são os mesmos que estão na página do commit no github: [https://github.com/aceleradora-TW/nao-me-calo/commit/1c83a58003a301e2b6dadb9ecbf6755f38681dac](https://github.com/aceleradora-TW/nao-me-calo/commit/1c83a58003a301e2b6dadb9ecbf6755f38681dac)

`app/admin/dashboard.rb`: tem um código comentado, acredito que seja exemplo. Se for, não é necessário manter lá.

`spec/models/admin_user_spec.rb`:  faltou escrever os testes =(

`db/seeds.rb`: cuidado para essa senha não ficar cadastrada em produção ou stage

`config/locales/devise.en.yml`: a parte de administração vai ser em inglês mesmo?

Outras observações:

- a url de administração vai aparecer em algum lugar na página ou as pessoas que vão administrar tem que guardar o link em algum lugar?

- `config/routes.rb`: é legal conferir na documentação do plugin se essa configuração não vai expor mais coisas que o necessário.
