### ISSUE TITLE
Avaliar local

### ISSUE THREAD

**Issue by pedrozan** [aceleradora-TW/nao-me-calo#2]
<b>Como</b> Josefa
<b>Quero</b> avaliar local
<b>Para</b> classificá-lo conforme minha experiência no ambiente

**Critérios de aceitação:**
- Botar nota
- Identificar usuário
- Confirmar envio
- Confirmação dos Termos de uso
- Mensagem de sucesso
- Explicações dos campos

**Tasks**

- Form: Formulário que pega os dados do usuário e as notas que ele deu para o local
- Infos do Local: Nome e endereço do local que aparecem em cima do formulário, para que o usuário possa se localizar

**Notas:**
- Ver com as P.O.s os dados e termos de uso.

**Comment by aolchik** [comment]
Será que o usuário quer se identificar para enviar a avaliação ou o não me calo precisa dos dados de identificação para atender questões legais? Esta história poderia ser escrita de forma diferente?

**Comment by WilliamCSA04** [comment]
Nós alteramos essa história. Diga o que acha.
Mudamos de usuário para avaliador porque o usuário não precisa ser um oprimido, pode ser alguem que viu algo acontecer e quer relatar.
