### ISSUE TITLE
Aumento tamanho da fonte

### ISSUE THREAD

**Issue by mibaratto** [aceleradora-TW/nao-me-calo#21]
#Como Josefa
Quero aumetar o tamanho da fonte 
Para poder ler com facilidade o conteúdo do site 

Critérios de aceitação:
 - Ter um botão para aumentar a fonte (no maximo duas vezes)

Tasks
 - Criar botão para aumentar texto

**Comment by thiagoxvo** [comment]
Pessoal, fiz o comentário no [commit](https://github.com/aceleradora-TW/nao-me-calo/commit/02854294dc0ed232374131787145de2888585e0a), mas acho que ele se perdeu aqui na issue.

No mais esta tudo validado e OK!
