### ISSUE TITLE
Visualizar dicas

### ISSUE THREAD

**Issue by pedrozan** [aceleradora-TW/nao-me-calo#3]
<b>Como</b> Josefa
<b>Quero</b> visualizar dicas 
<b>Para</b> obter ajuda

**Critérios de aceitação:**
- Mostrar informações úteis
- Explicações dos campos

**Notas:**
- Ver com as P.O.s as informações.

**Comment by aolchik** [comment]
Qual a diferença da #1 ?

**Comment by WilliamCSA04** [comment]
Modificamos a história para diferenciar as duas. O que tu acha?

**Comment by aolchik** [comment]
Acho que esta parece um cenário da outra, mas sugiro alinharmos isto na nossa próxima reunião de planejamento com a Ina!

**Comment by othman853** [comment]
### Code Review

Estória aprovada.

Observações:

Eu tentei rodar um leitor de tela nesta página de dicas e percebi que a ferramenta soletrou os links em maiúsculo (acho que ficou entendido que era uma sigla ao invés de uma frase).
