### ISSUE TITLE
Ver listagem

### ISSUE THREAD

**Issue by pedrozan** [aceleradora-TW/nao-me-calo#5]
<b>Como</b> Josefa
<b>Quero</b> ver listagem
<b>Para</b> poder visualizar lista dos últimos locais avaliados

**Critérios de aceitação:**
- Mostrar últimos cinco locais avaliados na home
- Redirecionar para perfil do local ao clicar no item da lista
- Nome, endereço e nota

**Tasks**
- Pegar e Ordenar: Buscar no Banco, ordenar e colocar na tela como link em uma tabela com nome e endereço

**Comment by aolchik** [comment]
Conseguem dar algum exempo de opções de ações?

**Comment by WilliamCSA04** [comment]
Neste link tem alguns exemplos https://naomecalo.herokuapp.com/dicas.html
