### ISSUE TITLE
Visualizar perfil do local

### ISSUE THREAD

**Issue by pedrozan** [aceleradora-TW/nao-me-calo#6]
<b>Como</b> Josefa
<b>Quero</b> visualizar perfil do local
<b>Para</b> visualizar informações mais detalhadas

**Critérios de aceitação:**
- Mostrar informações do local
- Botão para avaliação
- Mostrar nota

**Tasks**
- Criar Página: Mostra página de perfil com nome e informações do local, apresenta a nota e coloca um botão que redireciona para a página de avaliação criado na história #2 
- Cáclculo da Nota: Método que calcula a nota

**Notas:**
- Cálculo da nota
- Informações que vão aparecer (nome, endereço, telefone, site, as informações do google)

**Comment by pedrozan** [comment]
Estou comentando

**Comment by aolchik** [comment]
Será que vale segmentar mais: como josefa quero buscar um local para fazer um happy hour com meus amigos? As buscas podem ser diferentes? Talvez uma segmentação inicial facilite a validação do produto. Para pensar...

**Comment by WilliamCSA04** [comment]
Na última sessão entendemos que o sujeito era para ser algo mais abrangente e não algo tão específico.
Pensamos em trabalhar a questão das buscas diferentes como específicação desta história e não como histórias diferentes.
