### ISSUE TITLE
Visualizar ranking geral

### ISSUE THREAD

**Issue by WilliamCSA04** [aceleradora-TW/nao-me-calo#9]
**Como** Josefa
**Quero** visualizar lista geral dos locais
**Para** ver quais são os lugares com maior media

**Critérios de aceitação:**

- Exibir um ranking ordenado
- Botões para realizar a ordenação

**Task:**

- Ordenar melhor/pior: Criar a ordenação na lista da pagina inicial de acordo com as melhores e piores avaliações e os links para acessa-los.

**Nota:**

- Ver com POs quais são as ordenações possíveis.

**Comment by inajaraleppa** [comment]
Oi gente,

1. As ordenações serão: Maior nota e Menor nota.
2. Serão links ao invés de botões.

**Como** Josefa
**Quero** visualizar lista dos locais com maior e menor média
**Para** ver quais locais são ou não amigáveis para grupos oprimidos

**Comment by pedrozan** [comment]
Não entendemos bem o que tu queres dizer com ser links ao invés de botões, a ideia é ir para outra página?

**Comment by inajaraleppa** [comment]
Oi, o que quis dizer é que não precisa ter formato de botão, mas parecer com um link, assim como vcs fizeram na parte do filtro de Dicas. :)

**Comment by pedrozan** [comment]
Ok, entedemos agora =)

**Comment by mibaratto** [comment]
Oi Inajara,
Estavamos conversando sobre a questão de usar link ao invés de botão. Poderíamos usar abas como opção para selecionar os rakings?

**Comment by inajaraleppa** [comment]
Oi, Acho que abas não são muito acessíveis, dois links acima da tabela e conforme clica atualiza a tabela já é suficiente :)

**Comment by mibaratto** [comment]
...mantemos os links então ;)
